version: '3.7'

services:
  backend:
    build: .
    ports:
      - "3000:8080"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://alan:pascal101@localhost:5432/main
      MONGO_URI: mongodb://localhost:27017
      MONGO_DB: main
      JWT_SECRET: 3ADBRf4rPE9HNpA
    network_mode: host